/home/zyc/桌面/codeql-linux64/codeql/database_test/log/build-tracer.log
11
**/configure
<null>
10
0
0
**/do-prebuild
<null>
10
0
0
**/collect2
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
2
3
--linker
--semmle-linker-executable
${compiler}
0
**/lld*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
0
3
--linker
--semmle-linker-executable
${compiler}
0
**/*-ld*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
0
3
--linker
--semmle-linker-executable
${compiler}
0
**/ld*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
0
3
--linker
--semmle-linker-executable
${compiler}
0
**/armlink
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
0
3
--arm-linker
--semmle-linker-executable
${compiler}
0
**/icpc
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
4
2
--mimic
${compiler}
0
**/*++*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
4
2
--mimic
${compiler}
0
**/*cc*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
4
2
--mimic
${compiler}
0
**/*clang*
/home/zyc/桌面/codeql-linux64/codeql/cpp/tools/linux64/extractor
4
2
--mimic
${compiler}
0